config/routes.rb
OrionChess::Application.routes.draw do
  get 'welcome/about'
  devise_for :users
  resources :games
  resources :pieces, only: [:update]
  put 'games/:id/forfeit', to: 'games#forfeit', as: 'forfeit'
  resources :users, only: [:show]
  put 'games/:id/promote_pawn', to: 'games#promote_pawn', as: 'promote_pawn'

  root 'welcome#index'

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end

  def about
  end
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/welcome/_signin_modal.html.erb
<!-- Modal -->
<div class="modal fade" id="signin" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
          <h4 class="modal-title" id="myModalLabel">Sign in</h4>
          <br />
        </div>
      <div class="modal-body">
        <%= simple_form_for(resource, as: resource_name, url: session_path(resource_name)) do |f| %>
          <%= f.error_notification %>
          <div class="form-inputs">
            <%= f.input :login, required: false, autofocus: true, placeholder: "username or email" %>
            <%= f.input :password, required: false %>
            <br />
            <%= f.input :remember_me, as: :boolean if devise_mapping.rememberable? %>
          </div>
          <div class="form-actions">
          <br />
          <%= f.button :submit, "Sign in", :class => 'btn btn-primary float-left' %>
        </div>
        <% end %>
      </div>
      <div class="modal-footer">
        <%= render "devise/shared/links" %>
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div>

app/views/welcome/_signup_modal.html.erb
<!-- Modal -->
<div class="modal fade" id="signup" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
          <h4 class="modal-title" id="myModalLabel">Sign Up</h4>
          <br />
        </div>
      <div class="modal-body">
        <%= simple_form_for(resource, as: resource_name, url: registration_path(resource_name)) do |f| %>
          <%= f.error_notification %>
          <div class="form-inputs">
            <%= f.input :username, required: true, autofocus: true, placeholder: "Username" %>
            <%= f.input :email, required: true, placeholder: "Email" %>
            <%= f.input :password, hint: ("#{@minimum_password_length} characters minimum" if @minimum_password_length) %>
            <%= f.input :password_confirmation, required: true %>
          </div>
          <br />
          <div class="form-actions">
          <%= f.button :submit, "Sign up", :class => 'btn btn-small btn-success' %>
        </div>
      </div>
      <div class="modal-footer">
        <%= render "devise/shared/links" %>
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
      </div>
      <% end %>
    </div>
  </div>
</div>

app/views/welcome/about.html.erb
<div class="container text-center">
  <h1>Meet the Team</h1>
  <div class="row team">
    <div class="col-md-6">
      <%= image_tag("sean.jpg", size: "200")%>
      <h4> <%= link_to 'Sean Lovinger', 'https://github.com/smlovin2' %></h4>
      <p>(Insert clever bio here)</p>
    </div>
    <div class="col-md-6">
      <%= image_tag("yowon.jpg", size: "200") %>
      <h4><%= link_to 'Yowon Yoon', 'https://github.com/mrmonsk' %></h4>
      <p>Yowon Yoon is a rookie web developer from St. Paul, Minnesota. He is a lover of music, tennis, and hockey.</p>
    </div>
  </div>
</div>

app/views/welcome/index.html.erb
<script>
  $(window).scroll(function() {
  if($(this).scrollTop() > 70) {
    $('.navbar-fixed-top').addClass('opaque');
  }
  else {
    $('.navbar-fixed-top').removeClass('opaque');
  }
  });
</script>
<div class="container-fluid splash">
    <h2>OrionChess</h2>
    <br />
    <%= link_to 'Find a Game', games_path, :class => 'btn btn-default' %>
    <br />
    <div id="bottom"><p>A simple chess game built with Ruby on Rails</p></div>
</div>

<br />
<div class="container">
  <div class="row">
    <div class="left-well col-md-5 col-md-offset-1">
      <%= image_tag("chess_board.png") %>
    </div>
    <div class="right-well col-md-5">
      <p>ADD A DESCRIPTION HERE</p>
    </div>
  </div>
  <br />
  <div class="row">
    <div class="left-well col-md-5 col-md-offset-1">
      <%= image_tag("sample_code.png") %>
    </div>
    <div class="right-well col-md-5">
      <p>blah blah blah</p>
    </div>
  </div>
</div>