config/routes.rb
OrionChess::Application.routes.draw do
  get 'welcome/about'
  devise_for :users
  resources :games
  resources :pieces, only: [:update]
  put 'games/:id/forfeit', to: 'games#forfeit', as: 'forfeit'
  resources :users, only: [:show]
  put 'games/:id/promote_pawn', to: 'games#promote_pawn', as: 'promote_pawn'

  root 'welcome#index'

end

app/models/game.rb
class Game < ActiveRecord::Base
  has_many :pieces
  belongs_to  :white_player, class_name: 'User'
  belongs_to  :black_player, class_name: 'User'
  belongs_to  :winning_player, class_name: 'User'
  belongs_to  :active_player, class_name: 'User'

  scope :available, ->(current_user) { where('(white_player_id IS NULL OR black_player_id IS NULL) AND (white_player_id != ? OR black_player_id != ?)', current_user, current_user) }
  scope :users_games, ->(current_user) { where('white_player_id = ? OR black_player_id = ?', current_user.id, current_user.id) }

  after_create :populate_board!

  def populate_board!
    order_of_back_row = %w(Rook Knight Bishop Queen King Bishop Knight Rook)
    order_of_back_row.each_with_index do |type, column|
      Piece.create(type: type, game: self, color: 'black', row: 0, column: column)
      Piece.create(type: type, game: self, color: 'white', row: 7, column: column)

      Piece.create(type: 'Pawn', game: self, color: 'black', row: 1, column: column)
      Piece.create(type: 'Pawn', game: self, color: 'white', row: 6, column: column)
    end
  end

  def check?
    white_king = pieces.find_by(type: 'King', color: 'white')
    black_king = pieces.find_by(type: 'King', color: 'black')

    white_king.in_check? || black_king.in_check?
  end

  def forfeit(forfeiting_user)
    update_attributes(winning_player_id: other_player(forfeiting_user), over: true)
  end

  def other_player(player)
    player == white_player ? black_player.id : white_player.id
  end

  def pass_turn(player)
    update_attributes(active_player_id: other_player(player))
  end

  def users_game?(user)
    white_player == user || black_player == user
  end
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  before_action :set_game, :authenticate_user!, only: [:show, :edit, :update, :destroy]
  # GET /games
  # GET /games.json
  def index
    @available_games = Game.available(current_user)
    @users_games = Game.users_games(current_user)
  end

  # GET /games/1
  # GET /games/1.json
  def show
    @white_captured = Piece.white_captured(@game)
    @black_captured = Piece.black_captured(@game)
  end

  # GET /games/new
  def new
    @game = Game.new
  end

  # GET /games/1/edit
  def edit
  end

  # POST /games
  # POST /games.json
  def create
    @game = color_param == 'white' ? Game.new(white_player_id: user_param) : Game.new(black_player_id: user_param)

    respond_to do |format|
      if @game.save
        format.html { redirect_to @game, notice: 'Game was successfully created.' }
        format.json { render json: { redirect: game_path(@game) } }
      else
        format.html { render action: 'new' }
        format.json { render json: @game.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /games/1
  # PATCH/PUT /games/1.json
  def update
    color_param == 'white' ? current_game.update_attributes(white_player_id: user_param) : current_game.update_attributes(black_player_id: user_param)
    redirect_to game_path(current_game)
  end

  # DELETE /games/1
  # DELETE /games/1.json
  def destroy
    @game.destroy
    respond_to do |format|
      format.html { redirect_to games_url }
      format.json { head :no_content }
    end
  end

  def forfeit
    forfeiting_user = User.find(user_param)
    current_game.forfeit(forfeiting_user)
    redirect_to game_path(current_game), alert: 'Forfeit'
  end

  def promote_pawn
    pawn_to_promote = current_game.pieces.find(pawn_param)
    promoted_piece = pawn_to_promote.promote_pawn(promotion_param)
    respond_to do |format|
      format.html { render nothing: true, status: :ok }
      format.json { render nothing: true, json: { id: promoted_piece.id, chess_font_character: promoted_piece.chess_font_character }, status: :ok }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_game
    @game = Game.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def user_param
    params.require(:user_id)
  end

  def color_param
    params.require(:color)
  end

  def pawn_param
    params.require(:pawn_id)
  end

  def promotion_param
    params.require(:promotion_type)
  end

  def current_game
    @current_game ||= Game.find(params[:id])
  end
end

app/helpers/games_helper.rb
module GamesHelper
  def draw_piece(game, row, column)
    piece = game.pieces.find_by(row: row, column: column)

    return if piece.nil?

    content_tag(:span, piece.chess_font_character, class: 'piece', data: { update_url: piece_path(piece) })
  end

  def join_link(game)
    color = game.black_player.nil? ? 'black' : 'white'

    if game.users_game?(current_user)
      link_to 'Resume', game_path(game)
    else
      link_to 'Join', game_path(game, color: color, user_id: current_user.id), method: :patch
    end
  end
end

app/views/games/_form.html.erb
<%= form_for(@game) do |f| %>
  <% if @game.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@game.errors.count, "error") %> prohibited this game from being saved:</h2>

      <ul>
      <% @game.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    
  </div>
  <div class="actions">
    <%= link_to "Create Game", games_path(@game, game: { black_player_id: current_user.id }), method: :post, class: "btn btn-primary" %>
  </div>
<% end %>

app/views/games/_game.html.erb
<div class="game col-xs-6 col-xs-offset-3">
  <div class="top">
    <span><%= "Game #{game.id}" %></span>
    <div class="options">
      <%= join_link(game) %>
      <%= link_to game, method: :delete, data: { confirm: 'Are you sure?' }, class: 'delete glyphicon glyphicon-trash' do %>
      <% end %>
    </div>
  </div>
  <div class="players">
    <div class="white-player">
      <span class="white-piece">k</span>
      <% if game.white_player.nil? %>
        <span>: Open</span>
      <% else %>
        <span>: <%= game.white_player.username.nil? ? game.white_player.email : game.white_player.username %></span>
      <% end %>
    </div>
    <div class="black-player">
      <span class="black-piece">l</span>
      <% if game.black_player.nil? %>
        <span>: Open</span>
      <% else %>
        <span>: <%= game.black_player.username.nil? ? game.black_player.email : game.black_player.username %></span>
      <% end %>
    </div>
  </div>
</div>

app/views/games/edit.html.erb
<h1>Editing game</h1>

<%= render 'form' %>

<%= link_to 'Show', @game %> |
<%= link_to 'Back', games_path %>

app/views/games/index.html.erb
<script>
  $(function() {
    var playerColor;
    $('#new-game .piece-color').on('click', function() {
      $('#new-game span.selected').removeClass('selected');
      $(this).addClass('selected');

      $('#create-game').prop('disabled', false);

      if ($(this).text() === 'k') {
        playerColor = 'white';
      } else {
        playerColor = 'black';
      }
    });

    $('#create-game').on('click', function(event) {
      event.preventDefault();
      $.ajax({
        type: 'POST',
        url: '<%= games_path %>',
        dataType: 'json',
        data: { color: playerColor, user_id: $(this).data("user-id") }
      }).done(function(data) {
        $('#new-game').modal('hide');
        window.location.href = data.redirect;
      });
    });
  });
</script>

<div class="container">

  <div id="available-games">
    <h3 class="col-xs-6 col-xs-offset-3">Available Games</h3>
    <% if @available_games.empty? %>
      <h5 class="col-xs-6 col-xs-offset-3">There are currently no available_games.</h5>
    <% else %>
      <% @available_games.each do |game| %>
        <%= render partial: 'game', locals: {game: game} %>
      <% end %>
    <% end %>
  </div>

  <div id="users-games">
    <h3 class="col-xs-6 col-xs-offset-3">Your Games</h3>
    <% if @users_games.nil? %>
      <h5 class="col-xs-6 col-xs-offset-3">You currently don't have any games.</h5>
    <% else %>
      <% @users_games.each do |game| %>
        <%= render partial: 'game', locals: {game: game} %>
      <% end %>
    <% end %>
  </div>

  <div class="col-xs-6 col-xs-offset-3 text-center">
    <br />
    <%= link_to 'New Game', '#new_game', data: { toggle: 'modal', target: '#new-game' }, class: 'btn btn-primary' %>
  </div>
</div>

<!-- Modal -->
<div class="modal fade" id="new-game" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
          <h4 class="modal-title text-center" id="myModalLabel">New Game</h4>
          <br />
        </div>
      <div class="modal-body">
        <h5 class="text-center">Choose Your Color:</h5>
        <div class="text-center">
          <span class="piece-color">k</span>
          <span class="piece-color">l</span>
        </div>
      </div>
      <div class="modal-footer">
        <button class="btn btn-primary" id="create-game" disabled='disabled' data-user-id='<%= current_user.id %>'>Create Game</button>
      </div>
    </div>
  </div>
</div>

app/views/games/new.html.erb
<h1>New game</h1>

<%= render 'form' %>

<%= link_to 'Back', games_path %>

app/views/games/show.html.erb
<script>
  $(function() {
    var pawnId;
    var $droppedSpace;
    var $blackPlayerCapturedPieces = $('#black-player-info .captured-pieces');
    var $whitePlayerCapturedPieces = $('#white-player-info .captured-pieces');
    function is_in_back_row(piece) {
      if (piece.color == 'black'){
        return piece.row == 7;
      }else {
        return piece.row == 0;
      }
    }
    $('.piece').draggable({
      revert: 'invalid',
      containment: '#chessboard'
    });
    $('td').droppable({
      drop: function(ev, ui) {
        var drop_space_element = this;
        $.ajax({
          type: 'PUT',
          url: ui.draggable.data('update-url'),
          dataType: 'json',
          data: {piece: {row: $(this).parent().index(), column: $(this).index()}}
        }).done(function( data ) {
          if ($(drop_space_element).has('span.piece').length){
            var $capturedPieces = data.piece.color == 'white' ? $whitePlayerCapturedPieces : $blackPlayerCapturedPieces;
            $capturedPieces.append($(drop_space_element).children('span.piece').text());
            $(drop_space_element).children('span.piece').remove();
          }


          $(ui.draggable).detach().css({top: 0, left: 0}).appendTo(drop_space_element);

          var piece = data.piece;
          var type = data.piece_type;
          if (type === 'Pawn' && is_in_back_row(piece)){
            pawnId = piece.id;
            $droppedSpace = $(drop_space_element);
            $('#pawn-promotion').modal('show');
          }
        }).fail(function() {
          ui.draggable.animate({top: '0px', left: '0px'}, 'slow');
        });
      }
    });

    $('.promotion').on('click', function() {
      var piece_type = $(this).data('piece-type');
      $.ajax({
        type: 'PUT',
        url: '<%= promote_pawn_path(@game) %>',
        dataType: 'json',
        data: {promotion_type: piece_type, pawn_id: pawnId}
      }).done(function( data ) {
        $droppedSpace.html('<span class="piece" data-update-url="/pieces/'+ data.id + '" style="position: relative;">'+ data.chess_font_character + '</span>');
        $droppedSpace.children().draggable();
        $('#pawn-promotion').modal('hide');
      }).fail(function() {

      });
    });
  })
</script>

<div class="container">
  <p id="notice"><%= notice %></p>
  <div class="row text-center">
    <div id="black-player-info" class="col-md-3">
      <div class="player-name">
        <% if @game.black_player %>
          <h3><%= @game.black_player.username.nil? ? @game.black_player.email : @game.black_player.username %></h3>
        <% else %>
          <h3>Black Player</h3>
        <% end %>
      </div>
      <div class="captured-pieces col-xs-10 col-xs-offset-1">
        <%= @black_captured.map { |piece| piece.chess_font_character }.join %>
      </div>
    </div>
    <div class="col-md-6">
      <table id="chessboard">
        <% (0..7).each do |row| %>
        <tr>
            <% (0..7).each do |col| %>
            <td>
              <%= draw_piece(@game, row, col) %>
            </td>
          <% end %>
        </tr>
        <% end %>
      </table>
    </div>
    <div id="white-player-info" class="col-md-3">
      <div class="player-name">
        <% if @game.white_player %>
          <h3><%= @game.white_player.username.nil? ? @game.white_player.email : @game.white_player.username %></h3>
        <% else %>
          <h3>White Player</h3>
        <% end %>
      </div>
      <div class="captured-pieces col-xs-10 col-xs-offset-1">
        <%= @white_captured.map { |piece| piece.chess_font_character }.join %>
      </div>
    </div>
  </div>
</div>

<div class="game-links">
<%= link_to "Forfeit", forfeit_path(@game, user_id: current_user), method: :put, class: 'btn btn-danger' %>

<%= link_to 'Edit', edit_game_path(@game) %> |
<%= link_to 'Back', games_path %>
</div>

<!-- Modal -->
<div class="modal fade" id="pawn-promotion" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
          <h4 class="modal-title" id="myModalLabel">Promote pawn to:</h4>
        </div>
      <div class="pawn-promotion-modal-body">
        <% if current_user == @game.white_player %>
          <span class="promotion" data-piece-type='Queen'>q</span>
          <span class="promotion" data-piece-type='Knight'>k</span>
          <span class="promotion" data-piece-type='Rook'>r</span>
          <span class="promotion" data-piece-type='Bishop'>b</span>
        <% else %>
          <span class="promotion" data-piece-type='Queen'>w</span>
          <span class="promotion" data-piece-type='Knight'>l</span>
          <span class="promotion" data-piece-type='Rook'>t</span>
          <span class="promotion" data-piece-type='Bishop'>v</span>
        <% end %>
      </div>
    </div>
  </div>
</div>