config/routes.rb
OrionChess::Application.routes.draw do
  get 'welcome/about'
  devise_for :users
  resources :games
  resources :pieces, only: [:update]
  put 'games/:id/forfeit', to: 'games#forfeit', as: 'forfeit'
  resources :users, only: [:show]
  put 'games/:id/promote_pawn', to: 'games#promote_pawn', as: 'promote_pawn'

  root 'welcome#index'

end

app/views/layouts/_messages.html.erb
<% flash.each do |key, value| %>
  <div class="alert alert-<%= key %>">
    <a href="#" data-dismiss="alert" class="close">x</a>
    <ul>
      <li>
        <%= value %>
      </li>
    </ul>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>OrionChess</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
  <script>
    $(function () {
      $('.navbar-fixed-top').addClass('opaque');
    });
    //   { $("#myModal").modal({show:false });
  </script>
</head>
<body>
<%= render "welcome/signup_modal" %>
<%= render "welcome/signin_modal" %>

<div id="wrap">
  <!-- navbar begin -->
  <nav class="navbar navbar-default navbar-fixed-top navbar-text-center">
    <div class="container-fluid">
      <!-- Brand and toggle get grouped for better mobile display -->
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <%= link_to 'OrionChess', root_path, "class" => 'navbar-brand' %>
      </div>

      <!-- Collect the nav links, forms, and other content for toggling -->
      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        <ul class="nav navbar-nav">
          <li><%= link_to 'Join the game', games_path %></li>
        </ul>
        <ul class="nav navbar-nav navbar-right">
          <% if user_signed_in? %>
            <li><%= link_to 'My Profile', user_path(current_user) %></li>
            <li><%= link_to 'sign out', destroy_user_session_path, :method => :delete, class: "signout"%></li>'
          <% else %>
            <li><%= link_to 'Sign in', '#signin', "data-toggle" => "modal", :class => "signin"%></li>
            <li><%= link_to 'Sign up', '#signup', "data-toggle" => "modal", :class => "signup"%></li>
          <% end %>
        </ul>
      </div><!-- /.navbar-collapse -->
    </div><!-- /.container-fluid -->
  </nav>
  <!-- navbar end -->

<%= render 'layouts/messages' %>
<%= yield %>
  <br />

</div>



<div id="footer">
  <p><%= link_to 'About the Team', welcome_about_path %></p>
  <p><%= link_to 'View our code on Github', 'https://github.com/FirehoseProjectTeamOrion/OrionChess' %></p>
</div>

</body>
</html>